<template>
    <div class="loadingio-spinner-spinner-5ogy7a5d6mo">
        <div class="ldio-ktorgo38qlc">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</template>


<style lang="css" scoped>
@keyframes ldio-ktorgo38qlc {
    0% {
        opacity: 1;
    }
    100% {
        opacity: 0;
    }
}
.ldio-ktorgo38qlc div {
    left: 68.31px;
    top: 84.64500000000001px;
    position: absolute;
    animation: ldio-ktorgo38qlc linear 1.0869565217391304s infinite;
    background: #ff0033;
    width: 160.38000000000002px;
    height: 8.91px;
    border-radius: 80.19000000000001px / 4.455px;
    transform-origin: 80.19000000000001px 63.855000000000004px;
}
.ldio-ktorgo38qlc div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.9316770186335404s;
    background: #fe718d;
}
.ldio-ktorgo38qlc div:nth-child(2) {
    transform: rotate(51.42857142857143deg);
    animation-delay: -0.7763975155279502s;
    background: #f47e60;
}
.ldio-ktorgo38qlc div:nth-child(3) {
    transform: rotate(102.85714285714286deg);
    animation-delay: -0.6211180124223602s;
    background: #f8b26a;
}
.ldio-ktorgo38qlc div:nth-child(4) {
    transform: rotate(154.28571428571428deg);
    animation-delay: -0.4658385093167702s;
    background: #abbd81;
}
.ldio-ktorgo38qlc div:nth-child(5) {
    transform: rotate(205.71428571428572deg);
    animation-delay: -0.3105590062111801s;
    background: #849b87;
}
.ldio-ktorgo38qlc div:nth-child(6) {
    transform: rotate(257.14285714285717deg);
    animation-delay: -0.15527950310559005s;
    background: #6492ac;
}
.ldio-ktorgo38qlc div:nth-child(7) {
    transform: rotate(308.57142857142856deg);
    animation-delay: 0s;
    background: #637cb5;
}
.loadingio-spinner-spinner-5ogy7a5d6mo {
    width: 297px;
    height: 297px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
}
.ldio-ktorgo38qlc {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-ktorgo38qlc div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
